# Auto-populated Variables (set by Cloud Build)
# $PROJECT_ID
# $COMMIT_SHA
#
# Template Variables (set in trigger)
# $_IMAGE_NAME
# $_SSH_STRING
# $_ZONE
# $_HOME

steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          git submodule init &&
          git submodule update
  # build hugo site
  - name: 'sidpalas/cloud-builder-hugo:0.64.1'
  # build & push the container image
  - name: 'gcr.io/cloud-builders/docker'
    # Overriding entrypoint to allow for running two docker commands
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA . &&
        docker push     europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA
    # cleanup existing containers & redeploy with new container
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - $_SSH_STRING
      - --project
      - $PROJECT_ID
      - --zone
      - $_ZONE
      - --
      - docker run -d --restart=unless-stopped -p 8080:80 -p 4443:443 -v $_HOME/.caddy:/root/.caddy europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY