# Auto-populated Variables (set by Cloud Build)
# $PROJECT_ID
# $COMMIT_SHA
#
# Template Variables (set in trigger)
# $_IMAGE_NAME
# $_SSH_STRING
# $_ZONE
# $_HOME

steps:
  # Update submodules
  - name: 'gcr.io/cloud-builders/docker'