# Auto-populated Variables (set by Cloud Build)
# $PROJECT_ID
# $COMMIT_SHA
#
# Template Variables (set in trigger)
# $_IMAGE_NAME
# $_SSH_STRING
# $_ZONE
# $_HOME

steps:
  # Update submodules
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
        - -c
        - |
          docker build -v ".application_default_credentials.json":/gcp/credentials.json:ro --env GOOGLE_APPLICATION_CREDENTIALS=/gcp/credentials.json