# Auto-populated Variables (set by Cloud Build)
# $PROJECT_ID
# $COMMIT_SHA
#
# Template Variables (set in trigger)
# $_IMAGE_NAME
# $_SSH_STRING
# $_ZONE
# $_HOME

steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          git submodule init &&
          git submodule update
  - name: 'gcr.io/cloud-builders/docker'
options:
  logging: CLOUD_LOGGING_ONLY